spring.application.name=SubsidyDisbursementService

spring.datasource.url=jdbc:mysql://localhost:3306/agridb?createDatabaseIfNotExist=true

server.port=1234

spring.config.import=optional:configserver:http://localhost:8711
eureka.instance.prefer-ip-address=true

jwt.access.secret=DTFit9H2jFl8rrXRNjvTgjknNTHnblP4f7R2aGEP2eqA02iTXwZqvJ8csCZ5SmtN
jwt.refresh.secret=3df8kJopGIEHFiDMcT342EmYcEmw6sZr59DB0788HFBBZf86CffnQU3gnpVNiZfJ