spring.config.import=optional:configserver:

spring.application.name=APIGateway

server.port=9091



jwt.access.secret=DTFit9H2jFl8rrXRNjvTgjknNTHnblP4f7R2aGEP2eqA02iTXwZqvJ8csCZ5SmtN

jwt.access.ttl-seconds=900



# -------------------- AUTH SERVICE --------------------

spring.cloud.gateway.server.webflux.routes[0].id=authenticationservice

spring.cloud.gateway.server.webflux.routes[0].uri=lb://AUTHENTICATIONSERVICE

spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**



# -------------------- FARMER SERVICE --------------------

spring.cloud.gateway.server.webflux.routes[1].id=farmerservice

spring.cloud.gateway.server.webflux.routes[1].uri=lb://FARMERSERVICE

spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/farmers/**



# -------------------- DOCUMENT SERVICE --------------------

spring.cloud.gateway.server.webflux.routes[2].id=documentservice

spring.cloud.gateway.server.webflux.routes[2].uri=lb://FARMERDOCUMENTSERVICE

spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/documents/**



# -------------------- PROJECT SERVICE --------------------

spring.cloud.gateway.server.webflux.routes[3].id=projectservice

spring.cloud.gateway.server.webflux.routes[3].uri=lb://PROJECTSERVICE

spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/**



# -------------------- SCHEME SERVICE --------------------

spring.cloud.gateway.server.webflux.routes[4].id=schemeservice

spring.cloud.gateway.server.webflux.routes[4].uri=lb://SCHEMESERVICE

spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/policy/**,/application/**



# -------------------- SUBSIDY & DISBURSEMENT SERVICE --------------------

spring.cloud.gateway.server.webflux.routes[5].id=subsidydisbursementservice

spring.cloud.gateway.server.webflux.routes[5].uri=lb://SUBSIDYDISBURSEMENTSERVICE

spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/subsidies/**,/disbursements/**



# -------------------- NOTIFICATION SERVICE --------------------

spring.cloud.gateway.server.webflux.routes[6].id=notificationservice

spring.cloud.gateway.server.webflux.routes[6].uri=lb://NOTIFICATIONSERVICE

spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/notifications/**



# -------------------- COMPLIANCE SERVICE --------------------

spring.cloud.gateway.server.webflux.routes[7].id=complianceservice

spring.cloud.gateway.server.webflux.routes[7].uri=lb://COMPLIANCESERVICE

spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/api/**



# -------------------- EUREKA & CONFIG --------------------

spring.cloud.config.import-check.enabled=false

eureka.instance.prefer-ip-address=true



# Disable conflicting Gateway client metrics

spring.cloud.gateway.metrics.enabled=false





spring.cloud.gateway.server.webflux.routes[8].id=authenticationservice



spring.cloud.gateway.server.webflux.routes[8].uri=lb://AUTHENTICATIONSERVICE



spring.cloud.gateway.server.webflux.routes[8].predicates[0]=Path=/audit/**